require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe GroceryListsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # GroceryList. As you add validations to GroceryList, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GroceryListsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all grocery_lists as @grocery_lists" do
      grocery_list = GroceryList.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:grocery_lists)).to eq([grocery_list])
    end
  end

  describe "GET show" do
    it "assigns the requested grocery_list as @grocery_list" do
      grocery_list = GroceryList.create! valid_attributes
      get :show, {:id => grocery_list.to_param}, valid_session
      expect(assigns(:grocery_list)).to eq(grocery_list)
    end
  end

  describe "GET new" do
    it "assigns a new grocery_list as @grocery_list" do
      get :new, {}, valid_session
      expect(assigns(:grocery_list)).to be_a_new(GroceryList)
    end
  end

  describe "GET edit" do
    it "assigns the requested grocery_list as @grocery_list" do
      grocery_list = GroceryList.create! valid_attributes
      get :edit, {:id => grocery_list.to_param}, valid_session
      expect(assigns(:grocery_list)).to eq(grocery_list)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new GroceryList" do
        expect {
          post :create, {:grocery_list => valid_attributes}, valid_session
        }.to change(GroceryList, :count).by(1)
      end

      it "assigns a newly created grocery_list as @grocery_list" do
        post :create, {:grocery_list => valid_attributes}, valid_session
        expect(assigns(:grocery_list)).to be_a(GroceryList)
        expect(assigns(:grocery_list)).to be_persisted
      end

      it "redirects to the created grocery_list" do
        post :create, {:grocery_list => valid_attributes}, valid_session
        expect(response).to redirect_to(GroceryList.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved grocery_list as @grocery_list" do
        post :create, {:grocery_list => invalid_attributes}, valid_session
        expect(assigns(:grocery_list)).to be_a_new(GroceryList)
      end

      it "re-renders the 'new' template" do
        post :create, {:grocery_list => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested grocery_list" do
        grocery_list = GroceryList.create! valid_attributes
        put :update, {:id => grocery_list.to_param, :grocery_list => new_attributes}, valid_session
        grocery_list.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested grocery_list as @grocery_list" do
        grocery_list = GroceryList.create! valid_attributes
        put :update, {:id => grocery_list.to_param, :grocery_list => valid_attributes}, valid_session
        expect(assigns(:grocery_list)).to eq(grocery_list)
      end

      it "redirects to the grocery_list" do
        grocery_list = GroceryList.create! valid_attributes
        put :update, {:id => grocery_list.to_param, :grocery_list => valid_attributes}, valid_session
        expect(response).to redirect_to(grocery_list)
      end
    end

    describe "with invalid params" do
      it "assigns the grocery_list as @grocery_list" do
        grocery_list = GroceryList.create! valid_attributes
        put :update, {:id => grocery_list.to_param, :grocery_list => invalid_attributes}, valid_session
        expect(assigns(:grocery_list)).to eq(grocery_list)
      end

      it "re-renders the 'edit' template" do
        grocery_list = GroceryList.create! valid_attributes
        put :update, {:id => grocery_list.to_param, :grocery_list => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested grocery_list" do
      grocery_list = GroceryList.create! valid_attributes
      expect {
        delete :destroy, {:id => grocery_list.to_param}, valid_session
      }.to change(GroceryList, :count).by(-1)
    end

    it "redirects to the grocery_lists list" do
      grocery_list = GroceryList.create! valid_attributes
      delete :destroy, {:id => grocery_list.to_param}, valid_session
      expect(response).to redirect_to(grocery_lists_url)
    end
  end

end
